package com.queueless.controller;
import com.queueless.dao.ServiceDAO; import com.queueless.model.ServiceModel; import com.queueless.util.*; import jakarta.servlet.annotation.WebServlet; import jakarta.servlet.http.*; import java.io.*; import java.util.*;
@WebServlet("/api/services") public class ServiceServlet extends HttpServlet{
 private final ServiceDAO dao=new ServiceDAO();
 protected void doGet(HttpServletRequest req,HttpServletResponse res)throws IOException{try{boolean all=AuthUtil.staff(req);List<ServiceModel> a=dao.list(!all);res.setContentType("application/json;charset=UTF-8");StringBuilder b=new StringBuilder("{\"success\":true,\"services\":[");for(int i=0;i<a.size();i++){ServiceModel s=a.get(i);if(i>0)b.append(',');b.append("{\"id\":").append(s.id).append(",\"name\":\"").append(JsonUtil.esc(s.name)).append("\",\"description\":\"").append(JsonUtil.esc(s.description)).append("\",\"prefix\":\"").append(JsonUtil.esc(s.prefix)).append("\",\"averageTime\":").append(s.averageTime).append(",\"status\":\"").append(s.status).append("\"}");}b.append("]}");res.getWriter().write(b.toString());}catch(Exception e){res.setStatus(500);res.getWriter().write(JsonUtil.error("Unable to load services."));}}
 protected void doPost(HttpServletRequest req,HttpServletResponse res)throws IOException{if(AuthUtil.require(req,res)==null)return;try{String n=req.getParameter("name"),d=req.getParameter("description"),p=req.getParameter("prefix");int avg=Integer.parseInt(req.getParameter("averageTime"));validate(n,p,avg);dao.create(n.trim(),d==null?"":d.trim(),p.trim().toUpperCase(),avg);res.setContentType("application/json");res.getWriter().write(JsonUtil.ok("Service created successfully."));}catch(Exception e){res.setStatus(400);res.getWriter().write(JsonUtil.error(message(e,"Unable to create service.")));}}
 protected void doPut(HttpServletRequest req,HttpServletResponse res)throws IOException{if(AuthUtil.require(req,res)==null)return;try{long id=Long.parseLong(req.getParameter("id"));String n=req.getParameter("name"),d=req.getParameter("description"),p=req.getParameter("prefix"),st=req.getParameter("status");int avg=Integer.parseInt(req.getParameter("averageTime"));validate(n,p,avg);dao.update(id,n.trim(),d==null?"":d.trim(),p.trim().toUpperCase(),avg,"INACTIVE".equals(st)?"INACTIVE":"ACTIVE");res.setContentType("application/json");res.getWriter().write(JsonUtil.ok("Service updated successfully."));}catch(Exception e){res.setStatus(400);res.getWriter().write(JsonUtil.error(message(e,"Unable to update service.")));}}
 protected void doDelete(HttpServletRequest req,HttpServletResponse res)throws IOException{if(AuthUtil.require(req,res)==null)return;try{dao.deactivate(Long.parseLong(req.getParameter("id")));res.setContentType("application/json");res.getWriter().write(JsonUtil.ok("Service deactivated."));}catch(Exception e){res.setStatus(400);res.getWriter().write(JsonUtil.error("Unable to deactivate service."));}}
 private void validate(String n,String p,int a){if(n==null||n.trim().length()<2)throw new IllegalArgumentException("Service name is required.");if(p==null||!p.matches("[A-Za-z]{1,5}"))throw new IllegalArgumentException("Prefix must contain 1–5 letters.");if(a<1||a>240)throw new IllegalArgumentException("Average service time must be between 1 and 240 minutes.");}
 private String message(Exception e,String f){String m=e.getMessage();return m!=null&&m.contains("Duplicate")?"A service name or prefix already exists.":f;}
}
